routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('signin','AccountController@signin')->name('signin');
Route::post('login','AccountController@login')->name('login');

Route::get('signup','AccountController@signup')->name('signup');
Route::post('join','AccountController@join')->name('join');

Route::get('forgot','AccountController@forgot')->name('forgot');
Route::post('sentpassword','AccountController@sentpassword')->name('sentpassword');


Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('table')->name('table.')->group(function()
    {
        Route::get('index','TableController@index')->name('index');
        Route::post('index/{id}','TableController@AddFood')->name('AddFood');

        Route::get('create','TableController@create')->name('create');
        Route::post('store','TableController@store')->name('store');

        Route::get('edit/{id}','TableController@edit')->name('edit');
        Route::post('update/{id}','TableController@update')->name('update');

        Route::get('destroy/{id}','TableController@destroy')->name('destroy');

        Route::get('pay/{id}','TableController@pay')->name('pay');

        Route::get('cancle/{id}','TableController@cancle')->name('cancle');

    });
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('category')->name('category.')->group(function()
    {
        Route::get('index/{table_id}','CategoryController@index')->name('index');
        
        Route::get('create','CategoryController@create')->name('create');
        Route::post('store','CategoryController@store')->name('store');

        Route::get('edit/{id}','CategoryController@edit')->name('edit');
        Route::post('update/{id}','CategoryController@update')->name('update');

        Route::get('destroy/{id}','CategoryController@destroy')->name('destroy');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('product')->name('product.')->group(function()
    {
        Route::get('index/{category_Id}','ProductController@index')->name('index');
        
        Route::get('create/{category_Id}','ProductController@create')->name('create');
        Route::post('store','ProductController@store')->name('store');

        Route::get('edit/{id}','ProductController@edit')->name('edit');
        Route::post('update/{id}','ProductController@update')->name('update');

        Route::get('destroy/{id}','ProductController@destroy')->name('destroy');

        Route::get('addfood/{table_id}','ProductController@addfood')->name('addfood');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('bill')->name('bill.')->group(function()
    {
        Route::get('index','BillController@index')->name('index');
        Route::post('index/{id}','BillController@show')->name('show');
        
        Route::get('create','BillController@create')->name('create');
        Route::post('store','BillController@store')->name('store');

        Route::get('edit/{id}','BillController@edit')->name('edit');
        Route::post('update/{id}','BillController@update')->name('update');

        Route::get('destroy/{id}','BillController@destroy')->name('destroy');

        Route::get('list/{table_id}','BillController@list')->name('list');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('billinfo')->name('billinfo.')->group(function()
    {
        Route::get('index','BillinfoController@index')->name('index');
        
        Route::get('create','BillinfoController@create')->name('create');
        Route::post('store','BillinfoController@store')->name('store');

        Route::get('edit/{id}','BillinfoController@edit')->name('edit');
        Route::post('update/{id}','BillinfoController@update')->name('update');

        Route::get('destroy/{id}','BillinfoController@destroy')->name('destroy');


        Route::get('list/{bill_id}','BillinfoController@list')->name('list');
    });
});


Route::fallback(function () {
    echo "The website on the link you searched for does not exist";
});

app/Http/Controllers/Admin/TableController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB,Datetime;

class TableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

       $table = DB::table('table')->get();
       return View('cpadmin.modules.table.index')->with('table',$table);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View('cpadmin.modules.table.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    private function tableNameNotExists($name)
    {
        $record = DB::table('table')->where('name','=',$name)->get(); // get() trả ra 1 mảng object
        if(count($record) == 0)
        {
                return true;
        }
        else
        {
                return false;
        }
    }

    private function myFormatTableName($name)
    {
        $pattern = '/^[0-9]+$/';
        if(preg_match($pattern,$name))
        {
            return 1 ;
        }
        else
        {
            return 0 ;
        }
    }

    public function store(Request $request)
    {
          $name = $request->name;
            
          if($this->myFormatTableName($name) == 1)
          {
            if($this->tableNameNotExists($name) == true)
            {    
                $data = $request->except('_token');
                $data['created_at'] = new Datetime;
                $data['updated_at'] = new Datetime;
                DB::table('table')->insert($data);
                return redirect()->route('admin.table.create');
                
            }
            else
            {
                echo "Vui Lòng Nhập Lại Tên Khác";
                echo "<br>";
                echo "Tên Bàn Này $name Đã Tồn Tại";
            }
          }
          else
          {
            echo "Vui Lòng Nhập Đúng Format";
            echo "<br>";
            echo "Tên Bàn Chỉ Cho Phép Nhập Số";
          }
           
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('table')->where('id',$id)->first();// first trả ra 1 object 
        return View('cpadmin.modules.table.edit',['table'=>$data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $name = $request->name;
        if($this->myFormatTableName($name) == 1)
        {
            if($this->tableNameNotExists($name) == true)
            {
                $data = $request->except('_token');
                $data['updated_at'] = new Datetime;
                DB::table('table')->where('id',$id)->update($data);
                return redirect()->route('admin.table.index');
            }
            else
            {
                echo "Vui Lòng Nhập Lại Tên Khác";
                echo "<br>";
                echo "Tên Bàn Này $name Đã Tồn Tại";
            }
        }
        else
        {
            echo "Vui Lòng Nhập Đúng Format";
            echo "<br>";
            echo "Tên Bàn Chỉ Cho Phép Nhập Số";
        }
       
     
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('table')->where('id',$id)->delete();
        return redirect()->route('admin.table.index');
    }


    public function pay($id)
    {
        return "Chức năng làm sau";
    }

    public function cancle($id)
    {
        return "Chức năng làm sau"; 
    }
}

resources/views/cpadmin/modules/table/create.blade.php
@extends('cpadmin.master')
@section('title','Create Table')
@section('content')
<form action="{{route('admin.table.store')}}" method ="POST">
    @csrf
    <div class ="container bodyinfo">
        <div class = "row justify-content-center">
            <div class ="col-xl-9 col-lg-9 ">
                <div id="bg-purple" class ="card">
                    <div class ="card-header">
                        <div class="card-title text-center">
                            Thêm Bàn 
                        </div>
                    </div>
                    <div  class ="card-body">
                         <div class="form-row">
                            <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
                                <div class ="form-group">
                                <label for="name">Tên Bàn</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Example : 1 ">
                                </div> 
                             </div>   
                         </div>
                    </div>
                    <div class ="card-footer ">
                            <div class="form-row">
                                <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                                  <div class ="form-group"> 
                                    <input type="submit" value="submit"class="btn btn-plum form-control">
                                  </div>
                                </div>
                                <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                                    <div class="form-row">
                                     <a href="{{route('admin.table.index')}}"class="form-control btn btn-plum">Back</a>
                                    </div>
                                </div>
                            </div>
                        </div>   
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>   
@endsection

resources/views/cpadmin/modules/table/edit.blade.php
@extends('cpadmin.master')
@section('content')
<div class="container-fliud">
    <div class="row justify-content-center">
        <div class="col-9 col-sm-9 col-lg-9 col-xl-9">
            <form action="{{route('admin.table.update',['id'=>$table->id])}}" method="POST">
                @csrf
                <div id="bg-purple" class="card">
                    <div class="card-header">
                        <div class="card-title text-center">
                            Chỉnh Sửa <span class="text-primary">{{$table->name}}</span>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <div class="form-row">
                                <label for="name">Name</label>
                                <input type="text" id="name" name="name" class="form-control" value="{{$table->name}}">
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-12 col-sm-12 col-lg-6 col-xl-6 text-center">
                                    <input type="submit" value="submit" class="btn form-control btn-plum">
                                </div>
                                <div class="col-12 col-sm-12 col-lg-6 col-xl-6  text-center">
                                    <a href="{{route('admin.table.index')}}" class="btn  form-control btn-plum">Back</a>
                                </div>         
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/cpadmin/modules/table/index.blade.php
@extends('cpadmin.master')
@section('title','Danh Sách Bàn')
@section('content')
    <div class ="container-fluid">
        <div class ="row">
            <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
                <div id="bg-purple" class="card" >
                    <div class="card-header">
                        <div class="row">
                            <div class="col-12 col-xl-12 col-sm-12 col-lg-12">
                                <div class="title text-center">    
                                    Danh Sách Bàn    
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6  col-sm-6  col-xl-auto col-lg-auto text-center">
                               <a href="{{route('admin.table.create')}}" class="btn btn-plum  w-auto">Tạo Bàn</a>
                            </div>
                        </div>
                    </div>  
                    <div class="card-body">
                        <table id="example1"  class="table table-bordered">
                            <thead>
                                <tr>
                                    <th title="Số Thứ Tự">STT</th>
                                    <th title="Số ID Bàn">ID</th>
                                    <th title="Tên Bàn ">Tên Bàn</th>
                                    <th title="Trạng Thái">Trạng Thái</th>
                                    <th title="Tổng Tiền">Tổng Tiền</th>
                                    <th title="Thêm Món">Thêm Món</th>
                                    <th title="Xem Hóa Đơn">Xem Hóa Đơn </th>
                                    <th title="Thanh Toán">Thanh Toán Hóa Đơn</th>
                                    <th title="Hủy Bàn">Hủy Hóa Đơn</th>
                                    <th title="Chỉnh Sửa Bàn">Chỉnh Sửa Bàn</th>
                                    <th title="Xóa Bàn">Xóa Bàn</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($table as $tb)
                                 @if($tb->status == 1)
                                 <tr class="bg-plum">
                                   <td>{{$loop->iteration}}</td>
                                   <td>{{$tb->id}}</td>
                                   <td>{{$tb->name}}</td>
                                   <td> Có Người</td>
                                   <td>Chức năng làm sau</td>
                                   <td><a href="{{route('admin.category.index',['table_id'=>$tb->id])}}">Thêm Món</a></td>
                                   <td><a href="{{route('admin.bill.list',['table_id'=>$tb->id])}}">Xem Hóa Đơn</a></td>
                                   <td><a href="{{route('admin.table.pay',['id'=>$tb->id])}}">Thanh Toán Hóa Đơn</a></td>
                                   <td><a href="{{route('admin.table.cancle',['id'=>$tb->id])}}">Hủy Hóa Đơn</a></td>
                                   <td><a href="{{route('admin.table.edit',['id' => $tb->id])}}">Chỉnh sửa</a></td>
                                   <td><a href="{{route('admin.table.destroy',['id' => $tb->id])}}" onclick="return acceptDelete('Bạn Có Chắc Muốn Xóa Không')">Xóa Bàn</a></td>
                                </tr>
                                @else
                                <tr >
                                   <td>{{$loop->iteration}}</td>
                                   <td>{{$tb->id}}</td>
                                   <td>{{$tb->name}}</td>
                                   <td> Trống</td>
                                   <td>Chức Năng làm Sau</td>
                                   <td><a href="{{route('admin.category.index',['table_id'=>$tb->id])}}">Thêm Món</a></td>
                                   <td><a href="{{route('admin.bill.list',['table_id'=>$tb->id])}}">Xem Hóa Đơn</a></td>
                                   <td><a href="{{route('admin.table.pay',['id'=>$tb->id])}}">Thanh Toán Hóa Đơn</a></td>
                                   <td><a href="{{route('admin.table.cancle',['id'=>$tb->id])}}">Hủy Hóa Đơn</a></td>
                                   <td><a href="{{route('admin.table.edit',['id' => $tb->id])}}">Chỉnh sửa</a></td>
                                   <td><a href="{{route('admin.table.destroy',['id' => $tb->id])}}"  onclick="return acceptDelete('Bạn Có Chắc Muốn Xóa Không')">Xóa Bàn</a></td>
                                </tr> 
                                @endif  
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>                                 
                                    <th title="Số Thứ Tự">STT</th>
                                    <th title="Số ID Bàn">ID</th>
                                    <th title="Tên Bàn ">Tên Bàn</th>
                                    <th title="Trạng Thái">Trạng Thái</th>
                                    <th title="Tổng Tiền">Tổng Tiền</th>
                                    <th title="Thêm Món">Thêm Món</th>
                                    <th title="Xem Hóa Đơn">Xem Hóa Đơn </th>
                                    <th title="Thanh Toán">Thanh Toán Hóa Đơn</th>
                                    <th title="Hủy Bàn">Hủy Hóa Đơn</th>
                                    <th title="Chỉnh Sửa Bàn">Chỉnh Sửa Bàn</th>
                                    <th title="Xóa Bàn">Xóa Bàn</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-auto">
                                <a href="{{route('admin.table.create')}}" class="btn btn-plum">Tạo Bàn</a>
                            </div>
                        </div>
                    </div>
                 </div>
            </div>
        </div>
    </div>
@endsection