routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('signin','AccountController@signin')->name('signin');
Route::post('login','AccountController@login')->name('login');

Route::get('signup','AccountController@signup')->name('signup');
Route::post('join','AccountController@join')->name('join');

Route::get('forgot','AccountController@forgot')->name('forgot');
Route::post('sentpassword','AccountController@sentpassword')->name('sentpassword');


Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('table')->name('table.')->group(function()
    {
        Route::get('index','TableController@index')->name('index');
        Route::post('index/{id}','TableController@AddFood')->name('AddFood');

        Route::get('create','TableController@create')->name('create');
        Route::post('store','TableController@store')->name('store');

        Route::get('edit/{id}','TableController@edit')->name('edit');
        Route::post('update/{id}','TableController@update')->name('update');

        Route::get('destroy/{id}','TableController@destroy')->name('destroy');

        Route::get('pay/{id}','TableController@pay')->name('pay');

        Route::get('cancle/{id}','TableController@cancle')->name('cancle');

    });
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('category')->name('category.')->group(function()
    {
        Route::get('index/{table_id}','CategoryController@index')->name('index');
        
        Route::get('create','CategoryController@create')->name('create');
        Route::post('store','CategoryController@store')->name('store');

        Route::get('edit/{id}','CategoryController@edit')->name('edit');
        Route::post('update/{id}','CategoryController@update')->name('update');

        Route::get('destroy/{id}','CategoryController@destroy')->name('destroy');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('product')->name('product.')->group(function()
    {
        Route::get('index/{category_Id}','ProductController@index')->name('index');
        
        Route::get('create/{category_Id}','ProductController@create')->name('create');
        Route::post('store','ProductController@store')->name('store');

        Route::get('edit/{id}','ProductController@edit')->name('edit');
        Route::post('update/{id}','ProductController@update')->name('update');

        Route::get('destroy/{id}','ProductController@destroy')->name('destroy');

        Route::get('addfood/{table_id}','ProductController@addfood')->name('addfood');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('bill')->name('bill.')->group(function()
    {
        Route::get('index','BillController@index')->name('index');
        Route::post('index/{id}','BillController@show')->name('show');
        
        Route::get('create','BillController@create')->name('create');
        Route::post('store','BillController@store')->name('store');

        Route::get('edit/{id}','BillController@edit')->name('edit');
        Route::post('update/{id}','BillController@update')->name('update');

        Route::get('destroy/{id}','BillController@destroy')->name('destroy');

        Route::get('list/{table_id}','BillController@list')->name('list');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('billinfo')->name('billinfo.')->group(function()
    {
        Route::get('index','BillinfoController@index')->name('index');
        
        Route::get('create','BillinfoController@create')->name('create');
        Route::post('store','BillinfoController@store')->name('store');

        Route::get('edit/{id}','BillinfoController@edit')->name('edit');
        Route::post('update/{id}','BillinfoController@update')->name('update');

        Route::get('destroy/{id}','BillinfoController@destroy')->name('destroy');


        Route::get('list/{bill_id}','BillinfoController@list')->name('list');
    });
});


Route::fallback(function () {
    echo "The website on the link you searched for does not exist";
});

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB,Datetime;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($table_id)
    {
        $data = DB::table('category')->get();
        // dd($data);
        return View('cpadmin.modules.category.index' ,['category' => $data ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View('cpadmin.modules.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    private function myFormatCategoryName($name)
    { 
        $pattern ='/^[aàảãáạăằẳẵắặâầẩẫấậbcdđeèẻẽéẹêềểễếệfghiìỉĩíịjklmnoòỏõóọôồổỗốộơờởỡớợpqrstuùủũúụưừửữứựvwxyỳỷỹýỵz0-9_ ]+$/';
        if(preg_match($pattern,$name)) 
        {
            return 1 ; 
        }
        else 
        {
            return 0;
        }
    }
    private function categoryNameNotExists($name , $parent)
    {
        $record = DB::table('category')->where('name','=',$name)->where('parent','=',$parent)->get();
        if(count($record) == 0)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    public function store(Request $request)
    {
        $name = $request->name;
        $parent = $request->parent; 
        // dd($parent);
        if($this->myFormatCategoryName($name) == 1)
        {
            $result = $this->categoryNameNotExists($name,$parent);
            if($result == true)
            {
                $data = $request->except('_token');
                $data['created_at'] = new Datetime;
                $data['updated_at'] = new Datetime;
                DB::table('category')->insert($data);
                return redirect()->route('admin.category.create');
            }
            else
            {
               echo "Vui Lòng Nhập Lại Tên Khác";
               echo "<br>";
               echo "Tên Danh Mục Này $name Đã Tồn Tại";
            }
        }
        else
        {
            echo "Vui Lòng Nhập Đúng Format";
            echo "<br>";
            echo "Tên Danh Mục Không Được Có Ký Tự Đặc Biệt";
        }
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('category')->where('id',$id)->first();
        return View('cpadmin.modules.category.edit',['category'=>$data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $name = $request->name;
        $parent = $request->parent;
        if($this->myFormatCategoryName($name) == 1)
        {
            if($this->categoryNameNotExists($name,$parent) == true)
            {
                $data = $request->except('_token');
                $data['updated_at'] = new Datetime;
                DB::table('category')->where('id',$id)->update($data);
                return redirect()->route('admin.category.index');
            }
            else
            {
               echo "Vui Lòng Nhập Lại Tên Khác";
               echo "<br>";
               echo "Tên Danh Mục Này $name Đã Tồn Tại";
            }
        }
        else
        {
            echo "Vui Lòng Nhập Đúng Format";
            echo "<br>";
            echo "Tên Danh Mục Không Được Có Ký Tự Đặc Biệt";
        }
       
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('category')->where('id',$id)->delete();
        return redirect()->route('admin.category.index');
    }
}

resources/views/cpadmin/modules/category/create.blade.php
@extends('cpadmin.master')
@section('title','Tạo Danh Mục')
@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-12 col-lg-9 col-xl-9">
           <form action="{{route('admin.category.store')}}" method="POST">
               @csrf
              <div id="bg-purple" class="card"> 
              <div class="card-header text-center">
                  <div class="card-title">
                      Tạo Danh Mục
                  </div>
              </div>
              <div class="card-body">
                    <div class="form-group">
                       <label for="name">Tên</label>
                       <input type="text" id="name" name="name" class="form-control" >
                    </div>
                    <div class="form-group">
                        <label for="parent">Parent</label>
                        <select name="parent" id="parent" class="form-control">
                            <option value="1">1</option>
                        </select>
                    </div>
               </div>
               <div class="card-footer">
                    <div class="form-row">
                        <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                            <input type="submit" value="submit" class="btn btn-plum form-control">
                        </div>
                        <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                            <a href="{{route('admin.category.index')}}" class="btn btn-plum form-control">Back</a>
                        </div>
                    </div>
               </div>
            </div>
           </form>
        </div>
    </div>
</div>
@endsection

resources/views/cpadmin/modules/category/edit.blade.php
@extends('cpadmin.master')
@section('title','Chỉnh Sửa Danh Mục')
@section('content')
<form action="{{route('admin.category.update',['id'=>$category->id])}}" method="POST">
@csrf
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-12 col-lg-9 col-xl-9">
          <div  id="bg-purple" class="card">
            <div class="card-header">
                <div class="card-title text-center">
                    Chỉnh Sửa Danh Mục <span class="text-primary"> {{$category->name}} </span>
                </div>
            </div>
            <div class="card-body">
                <div class="form-row">
                    <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <label for="name">name</label>
                            <input type="text" name="name"  id="name" value="{{$category->name}}" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
                        <div class="form-group">
                            <label for="parent">Parent</label>
                            <select name="parent" id="parent" class="form-control">
                                <option value="1" {{($category->parent == 1)? 'selected' : ''}}>1</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="form-row">
                    <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                     <div class="form-group"> 
                        <input type="submit" class="btn btn-plum form-control" value="submit">
                     </div>
                    </div>
                    <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                        <div class="form-group">
                         <a href="{{route('admin.category.index')}}" class="btn btn-plum form-control">Back</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
</form>
@endsection()

resources/views/cpadmin/modules/category/index.blade.php
@extends('cpadmin.master')
@section('title','Danh Sách Danh Mục')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
          <div id="bg-purple" class="card">
             <div class="card-header">
                 <div class="row">
                    <div class="col-12 col-lg-12 col-sm-12 col-xl-12">
                       <div class="card-title text-center">
                          Danh Sách Danh Mục
                       </div>
                    </div>
                 </div>
                 <div class="row">
                      <div class="col-6 col-xl-6 col-sm-auto col-lg-auto">
                           <a href="{{route('admin.category.create')}}" class="btn btn-plum">Tạo Danh Mục</a>
                     </div>
                 </div>
             </div>
             <div  class="card-body">
               <table id="example1" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>ID</th>
                            <th>Tên Danh Mục</th>
                            <th>Parent</th>
                            <th>Ngày Tạo</th>
                            <th>Ngày Cập Nhật</th>
                            <th>Thêm Sản Phẩm Cho Danh Mục Này</th>
                            <th>Xem Sản Phẩm Của Danh Mục Này</th>
                            <th>Chỉnh Sửa Danh Mục</th>
                            <th>Xóa Danh Mục</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($category as $item)
                        <tr>
                            <td>{{$loop->iteration}}</td>
                            <td>{{$item->id}}</td>
                            <td>{{$item->name}}</td>
                            <td>{{$item->parent}}</td>
                            <td>{{$item->created_at}}</td>
                            <td>{{$item->updated_at}}</td>
                            <td title="Thêm Sản Phẩm Cho Danh Mục {{$item->name}}"><a href="{{route('admin.product.create',['category_Id'=>$item->id])}}">Thêm</a></td>
                            <td title="Xem Sản Phẩm Cho Danh Mục {{$item->name}}"><a href="{{route('admin.product.index',['category_Id'=>$item->id])}}">Xem</a></td>
                            <th title="Chỉnh Sửa Danh Mục {{$item->name}}"><a href="{{route('admin.category.edit',['id' =>$item->id])}}" >Chỉnh Sửa</a></th>
                            <th title="Xóa Danh Mục {{$item->name}}"><a href="{{route('admin.category.destroy',['id' =>$item->id])}}" onclick="return acceptDelete('Bạn Có chắc Muốn Xóa Danh Mục Này')">Xóa</a></th>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                       <tr>
                            <th>STT</th>
                            <th>ID</th>
                            <th>Tên</th>
                            <th>Parent</th>
                            <th>Ngày Tạo</th>
                            <th>Ngày Cập Nhật</th>
                            <th>Thêm Sản Phẩm Cho Danh Mục Này</th>
                            <th>Xem Sản Phẩm Của Danh Mục Này</th>
                            <th>Chỉnh Sửa Danh Mục</th>
                            <th>Xóa Danh Mục</th>
                       </tr>
                    </tfoot>
               </table>
             </div>
             <div class="card-footer">
               <div class="row">
                  <div class="col-12 col-sm-12 col-lg-auto col-xl-auto">
                    <a href="{{route('admin.category.create')}}" class="btn btn-plum">Tạo Danh Mục</a>
                  </div>
               </div>
             </div>
          </div>
        </div>
    </div>
</div>
@endsection