routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('signin','AccountController@signin')->name('signin');
Route::post('login','AccountController@login')->name('login');

Route::get('signup','AccountController@signup')->name('signup');
Route::post('join','AccountController@join')->name('join');

Route::get('forgot','AccountController@forgot')->name('forgot');
Route::post('sentpassword','AccountController@sentpassword')->name('sentpassword');


Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('table')->name('table.')->group(function()
    {
        Route::get('index','TableController@index')->name('index');
        Route::post('index/{id}','TableController@AddFood')->name('AddFood');

        Route::get('create','TableController@create')->name('create');
        Route::post('store','TableController@store')->name('store');

        Route::get('edit/{id}','TableController@edit')->name('edit');
        Route::post('update/{id}','TableController@update')->name('update');

        Route::get('destroy/{id}','TableController@destroy')->name('destroy');

        Route::get('pay/{id}','TableController@pay')->name('pay');

        Route::get('cancle/{id}','TableController@cancle')->name('cancle');

    });
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('category')->name('category.')->group(function()
    {
        Route::get('index/{table_id}','CategoryController@index')->name('index');
        
        Route::get('create','CategoryController@create')->name('create');
        Route::post('store','CategoryController@store')->name('store');

        Route::get('edit/{id}','CategoryController@edit')->name('edit');
        Route::post('update/{id}','CategoryController@update')->name('update');

        Route::get('destroy/{id}','CategoryController@destroy')->name('destroy');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('product')->name('product.')->group(function()
    {
        Route::get('index/{category_Id}','ProductController@index')->name('index');
        
        Route::get('create/{category_Id}','ProductController@create')->name('create');
        Route::post('store','ProductController@store')->name('store');

        Route::get('edit/{id}','ProductController@edit')->name('edit');
        Route::post('update/{id}','ProductController@update')->name('update');

        Route::get('destroy/{id}','ProductController@destroy')->name('destroy');

        Route::get('addfood/{table_id}','ProductController@addfood')->name('addfood');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('bill')->name('bill.')->group(function()
    {
        Route::get('index','BillController@index')->name('index');
        Route::post('index/{id}','BillController@show')->name('show');
        
        Route::get('create','BillController@create')->name('create');
        Route::post('store','BillController@store')->name('store');

        Route::get('edit/{id}','BillController@edit')->name('edit');
        Route::post('update/{id}','BillController@update')->name('update');

        Route::get('destroy/{id}','BillController@destroy')->name('destroy');

        Route::get('list/{table_id}','BillController@list')->name('list');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('billinfo')->name('billinfo.')->group(function()
    {
        Route::get('index','BillinfoController@index')->name('index');
        
        Route::get('create','BillinfoController@create')->name('create');
        Route::post('store','BillinfoController@store')->name('store');

        Route::get('edit/{id}','BillinfoController@edit')->name('edit');
        Route::post('update/{id}','BillinfoController@update')->name('update');

        Route::get('destroy/{id}','BillinfoController@destroy')->name('destroy');


        Route::get('list/{bill_id}','BillinfoController@list')->name('list');
    });
});


Route::fallback(function () {
    echo "The website on the link you searched for does not exist";
});

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB , Datetime;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index($category_Id)
    {   
        // select * from product where category_id = $category_Id and where status = 0 ;
        $object_Category = DB::table('category')->where('id','=',$category_Id)->first();
        $data = DB::table('product')->where('category_id','=',$category_Id)->where('status','=',0)->get();
        return View('cpadmin.modules.product.index',['product'=>$data],['object_Category'=>$object_Category]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($category_Id)
    {
        // select name form category where id = $category_Id;
        $category_Name = DB::table('category')->where('id','=',$category_Id)->value('name');
        return View('cpadmin.modules.product.create',['category_Id'=>$category_Id] ,['category_Name'=> $category_Name]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    private function productNameNotExists($name)
    {   
       // select id form `product` where `name` = $name;
        $record = DB::table('product')->where('name','=',$name)->get('id');
        if(count($record) == 0)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    private function myFormatProductName($name)
    {
        $pattern =  '/^[aàảãáạăằẳẵắặâầẩẫấậbcdđeèẻẽéẹêềểễếệfghiìỉĩíịjklmnoòỏõóọôồổỗốộơờởỡớợpqrstuùủũúụưừửữứựvwxyỳỷỹýỵz0-9_ ]+$/';
        if(preg_match($pattern,$name))
        {
            return 1 ;
        }
        else
        {
            return 0;
        }
    }
    private function myFormatProductPrice($price)
    {
        $pattern = '/^[0-9]+$/'; 
        if(preg_match($pattern,$price))
        {
            return 1 ;
        }
        else
        {
            return 0;
        }
    }

    public function store(Request $request)
    {
         //insert into `product`(`name`,`category_id`,`price`) values()
        
        
         $name = $request->name;
         $price = $request->price;
         if($this->myFormatProductName($name) == 1)
         {
             if($this->myFormatProductPrice($price) == 1)
             {
                $Result = $this->productNameNotExists($name);
                if($Result == true)
                {
                     $data = $request->except('_token');
                     $data['created_at'] = new Datetime;
                     $data['updated_at'] = new Datetime;
                     DB::table('product')->insert($data);
                return redirect()->route('admin.product.create',['category_Id'=>$request->category_Id]);
                }
                else
                {
                    echo "Vui Lòng Nhập Lại Tên Khác";
                    echo "<br>";
                    echo "Tên Sản Phẩm $name Đã Tồn Tại";
                }
            }
            else
            {
                echo "Vui Lòng Nhập Đúng Format";
                echo "<br>";
                echo "Tên Sản Phẩm Không Được Nhập Ký Tự Đặc Biệt";
            }
         }
         else
         {
            echo "Vui Lòng Nhập Lại Trường Tên";
            echo "<Br>";
            echo " Tên Không Cho Phép Nhập Ký Tự Đặt Biệt ";
         }
      
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
            // Get Name And Id Of Category
            // truy ngược 
            // Bằng Cách join category with product
            // select A.name , A.ID from category as A join product as B on A.ID = B.category_id
            //  where B.ID = $id ; 
            $object_Category = DB::table('category')
            ->join('product','category.id','=','product.category_id')
            ->select('category.name','category.id')
            ->where('product.id','=',$id)
            ->first(); // first trả ra 1 object not 1 array object
            $data = DB::table('product')->where('id','=',$id)->where('status','=',0)->first();
            return View('cpadmin.modules.product.edit',['product'=>$data],['object_Category'=>$object_Category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $name = $request->name;
        $price = $request->price;
        if($this->myFormatProductName($name) == 1)
        {
            if($this->myFormatProductPrice($price) == 1)
            {
               $Result = $this->productNameNotExists($name);
               if($Result == true)
               {
                    $data = $request->except('_token');
                    $data['updated_at'] = new Datetime;
                    DB::table('product')->where('id','=',$id)->update($data);
               return redirect()->route('admin.product.create',['category_Id'=>$request->category_Id]);
               }
               else
               {
                   echo "Vui Lòng Nhập Lại Tên Khác";
                   echo "<br>";
                   echo "Tên Sản Phẩm $name Đã Tồn Tại";
               }
           }
           else
           {
               echo "Vui Lòng Nhập Đúng Format";
               echo "<br>";
               echo "Tên Sản Phẩm Không Được Nhập Ký Tự Đặc Biệt";
           }
        }
        else
        {
           echo "Vui Lòng Nhập Lại Trường Tên";
           echo "<Br>";
           echo " Tên Không Cho Phép Nhập Ký Tự Đặt Biệt ";
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $object_Category = DB::table('category')
        ->join('product','category.id','=','product.category_id')
        ->where('product.id','=',$id)
        ->select('category.name','category.id')
        ->first(); 
        DB::table('product')->where('id','=',$id)->delete();
        return redirect()->route('admin.product.index',['category_Id'=>$object_Category->id]);
    }

    public function addfood($table_id)
    {
        return "Chức Năng Này Làm Sau";
    }
}

resources/views/cpadmin/modules/product/create.blade.php
@extends('cpadmin.master')
@section('title','Tạo Sản Phẩm Của Danh Mục')
@section('content')
<form action="{{route('admin.product.store')}}" method="POST">
@csrf
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-12 col-lg-9 col-xl-9">
                <div id="bg-purple" class="card">
                    <div class="card-header">
                        <div class="row ">
                           <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
                                <div class="card-title text-center">
                                 Tạo Sản Phẩm Của Danh Mục <span class="text-primary">{{$category_Name}} </span>
                                </div>
                           </div> 
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 col-sm-12 col-lg-12">
                                <div class="form-group">
                                    <label for="nameOfcategory">Danh Mục</label>
                                    <select name="category_Id" id="nameOfcategory" class="form-control">
                                      <option value="{{$category_Id}}">{{$category_Name}}</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
                                <div class="form-group">
                                   <label for="name">Tên</label>
                                   <input type="text" id="name" name="name" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
                                <div class="form-group">
                                   <label for="price">Giá</label>
                                   <input type="text" id="price" name="price" class="form-control">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="form-row">
                            <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                                <div class="form-group">
                                    <input type="submit" class="btn btn-plum form-control" value="submit">
                                </div>
                            </div>
                            <div  class="col-12 col-sm-12 col-lg-6 col-xl-6">
                                    <div class="form-group">
                                       <a href="{{route('admin.category.index')}}" class="btn btn-plum form-control">Back</a> 
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/cpadmin/modules/product/edit.blade.php
@extends('cpadmin.master')
@section('title','Chỉnh Sửa Sản Phẩm')
@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-12 col-lg-9 col-xl-9">
              <form action="{{route('admin.product.update',['id'=>$product->id])}}" method="POST">
                <div id="bg-purple" class="card">
                    <div class="card-header">
                        <div class="card-title">
                           <div class="row">
                             <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
                                <div class="card-title text-center">
                                    Chỉnh Sửa Sản Phẩm <span class="text-primary">{{$product->name}} </span>
                                </div>
                             </div>
                           </div>
                        </div>
                    </div>
                    <div class="card-body">
                            @csrf
                            <div class="form-row">
                                <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
                                    <div class="form-group">
                                        <label for="NameOfCategory">Danh Mục</label>
                                        <select name="category_Id" id="NameOfCategory" class="form-control">
                                            <option value="{{$object_Category->id}}" >{{$object_Category->name}}</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
                                    <div class="form-group">
                                        <label for="name">Tên</label>
                                        <input type="text" name="name" id="name" class="form-control" value="{{$product->name}}">
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
                                    <div class="form-group">
                                        <label for="price">Giá</label>
                                        <input type="text" name="price" id="price" class="form-control" value={{$product->price}}>
                                    </div>
                                </div>
                            </div>
                     </div>
                    <div class="card-footer">
                        <div class="form-row">
                            <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                                <div class="form-group">
                                    <input type="submit" class=" form-control btn btn-plum" value="submit">
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                                <div class="form-group">
                                    <a href="{{route('admin.product.index',['category_Id'=>$object_Category->id])}}" class="form-control btn btn-plum">Back</a>
                                </div>               
                            </div>
                        </div>
                    </div>
                </div>
             </form>
            </div>
        </div>
    </div>
@endsection

resources/views/cpadmin/modules/product/index.blade.php
@extends('cpadmin.master')
@section('title','Danh Sách Sản Phẩm ')
@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
            <div id="bg-purple" class="card">
                <div class="card-header">
                    <div class="card-title">
                        Danh Sách Sản Phẩm Của Danh Mục <span class="text-primary">{{$object_Category->name}}</span>
                    </div>
                </div>
                <div class="card-body">
                    <table id="example1" class="table table-bordered">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>ID</th>
                                <th>Tên</th>
                                <th>Gía</th>
                                <th>Ngày Tạo</th>
                                <th>Ngày Chỉnh Sửa Gần Nhất</th>
                                <th>Thêm Món</th>
                                <th>Chỉnh Sửa</th>
                                <th>Xóa</th>
                            </tr>  
                        </thead>
                        <tbody>
                            @foreach($product as $item)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$item->id}}</td>
                                <td>{{$item->name}}</td>
                                <td> {{$item->price}}</td>
                                <td>{{$item->created_at}}</td>
                                <td>{{$item->updated_at}}</td>
                                <td><a href="{{route('admin.product.addfood',['table_id'=>1])}}">Thêm Món </a></td>
                                <td><a href="{{route('admin.product.edit',['id'=>$item->id])}}">Chỉnh Sửa</a></td>
                                <td><a href="{{route('admin.product.destroy',['id'=>$item->id])}}">Xóa</a></td>
                            </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>STT</th>
                                <th>ID</th>
                                <th>Tên</th>
                                <th>Gía</th>
                                <th>Ngày Tạo</th>
                                <th>Ngày Chỉnh Sửa Gần Nhất</th>
                                <th>Thêm Món</th>
                                <th>Chỉnh Sửa</th>
                                <th>Xóa</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection