routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('signin','AccountController@signin')->name('signin');
Route::post('login','AccountController@login')->name('login');

Route::get('signup','AccountController@signup')->name('signup');
Route::post('join','AccountController@join')->name('join');

Route::get('forgot','AccountController@forgot')->name('forgot');
Route::post('sentpassword','AccountController@sentpassword')->name('sentpassword');


Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('table')->name('table.')->group(function()
    {
        Route::get('index','TableController@index')->name('index');
        Route::post('index/{id}','TableController@AddFood')->name('AddFood');

        Route::get('create','TableController@create')->name('create');
        Route::post('store','TableController@store')->name('store');

        Route::get('edit/{id}','TableController@edit')->name('edit');
        Route::post('update/{id}','TableController@update')->name('update');

        Route::get('destroy/{id}','TableController@destroy')->name('destroy');

        Route::get('pay/{id}','TableController@pay')->name('pay');

        Route::get('cancle/{id}','TableController@cancle')->name('cancle');

    });
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('category')->name('category.')->group(function()
    {
        Route::get('index/{table_id}','CategoryController@index')->name('index');
        
        Route::get('create','CategoryController@create')->name('create');
        Route::post('store','CategoryController@store')->name('store');

        Route::get('edit/{id}','CategoryController@edit')->name('edit');
        Route::post('update/{id}','CategoryController@update')->name('update');

        Route::get('destroy/{id}','CategoryController@destroy')->name('destroy');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('product')->name('product.')->group(function()
    {
        Route::get('index/{category_Id}','ProductController@index')->name('index');
        
        Route::get('create/{category_Id}','ProductController@create')->name('create');
        Route::post('store','ProductController@store')->name('store');

        Route::get('edit/{id}','ProductController@edit')->name('edit');
        Route::post('update/{id}','ProductController@update')->name('update');

        Route::get('destroy/{id}','ProductController@destroy')->name('destroy');

        Route::get('addfood/{table_id}','ProductController@addfood')->name('addfood');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('bill')->name('bill.')->group(function()
    {
        Route::get('index','BillController@index')->name('index');
        Route::post('index/{id}','BillController@show')->name('show');
        
        Route::get('create','BillController@create')->name('create');
        Route::post('store','BillController@store')->name('store');

        Route::get('edit/{id}','BillController@edit')->name('edit');
        Route::post('update/{id}','BillController@update')->name('update');

        Route::get('destroy/{id}','BillController@destroy')->name('destroy');

        Route::get('list/{table_id}','BillController@list')->name('list');
    });
});



Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function()
{
    Route::prefix('billinfo')->name('billinfo.')->group(function()
    {
        Route::get('index','BillinfoController@index')->name('index');
        
        Route::get('create','BillinfoController@create')->name('create');
        Route::post('store','BillinfoController@store')->name('store');

        Route::get('edit/{id}','BillinfoController@edit')->name('edit');
        Route::post('update/{id}','BillinfoController@update')->name('update');

        Route::get('destroy/{id}','BillinfoController@destroy')->name('destroy');


        Route::get('list/{bill_id}','BillinfoController@list')->name('list');
    });
});


Route::fallback(function () {
    echo "The website on the link you searched for does not exist";
});

app/Http/Controllers/Admin/BillController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB,DateTime;
class BillController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DB::table('bill')->get();
        return view('cpadmin.modules.bill.index',['bills'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cpadmin.modules.bill.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data  = $request->except('_token');
        $data['created_at'] = new DateTime;
        $data['updated_at'] = new DateTime;
        $data['cost'] = 0;
        $data['datetimecheckout'] = new DateTime;
        $data['datetimecheckin'] = new DateTime;
        $data = DB::table('bill')->insert($data);
        return redirect()->route('admin.bill.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data =DB::table('bill')->where('id',$id)->first();
        return view('cpadmin.modules.bill.edit',['billesssssssss'=>$data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data  = $request->except('_token');
      
      
        $data['cost'] = 0;
        
        $data['updated_at'] = new DateTime;
        $data = DB::table('bill')->where('id',$id)->update($data);
        return redirect()->route('admin.bill.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = DB::table('bill')->where('id',$id)->delete();
        return redirect()->route('admin.bill.index');
    }

    public function list($table_id)
    {
        $bill = DB::table('bill')->where('table_id','=',$table_id)->where('status','=',0)->first();
        return View('cpadmin.modules.bill.list',['bill'=>$bill]);
    }
}

resources/views/cpadmin/modules/bill/create.blade.php
@extends('cpadmin.master')
@section('title','Tạo Bill ')
@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-12 col-lg-9 col-xl-9">
           <form action="{{route('admin.bill.store')}}" method="POST">
               @csrf
              <div id="bg-purple" class="card"> 
              <div class="card-header text-center">
                  <div class="card-title">
                      Tạo Bill
                  </div>
              </div>
              <div class="card-body">
                    <div class="form-group">
                       <label for="name">Giảm giá</label>
                       <input type="text" id="name" name="discount" class="form-control" >
                    </div>
                   
                    
                    <div class="form-group">
                        <label for="name">Ghi chú</label>
                        <input type="text" id="name" name="note" class="form-control" >
                    </div>
                    <div class="form-group">
                        <label for="name">Table_id</label>
                        <input type="text" class="form-control" name="table_id" placeholder="Enter Image">
                    </div>
               </div>
               <div class="card-footer">
                    <div class="form-row">
                        <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                            <input type="submit" value="submit" class="btn btn-plum form-control">
                        </div>
                        <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                            <a href="{{route('admin.bill.index')}}" class="btn btn-plum form-control">Back</a>
                        </div>
                    </div>
               </div>
            </div>
           </form>
        </div>
    </div>
</div>
@endsection

resources/views/cpadmin/modules/bill/edit.blade.php
@extends('cpadmin.master')
@section('title','Edit Bill ')
@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-12 col-lg-9 col-xl-9">
           <form action="{{route('admin.bill.update',['id'=>$billesssssssss->id])}}" method="POST">
               @csrf
              <div id="bg-purple" class="card"> 
              <div class="card-header text-center">
                  <div class="card-title">
                     Sửa Bill
                  </div>
              </div>
              <div class="card-body">
                    <div class="form-group">
                       <label for="name">Giảm giá</label>
                       <input type="text" id="name" name="discount" value="{{$billesssssssss->discount}}" class="form-control" >
                    </div>
                   
                    
                    <div class="form-group">
                        <label for="name">Ghi chú</label>
                        <input type="text" id="name" name="note"  value="{{$billesssssssss->note}}"class="form-control" >
                    </div>
                    <div class="form-group">
                        <label for="name">Table_id</label>
                        <input type="text" class="form-control" value="{{$billesssssssss->table_id}}" name="table_id" placeholder="Enter Image">
                    </div>
               </div>
               <div class="card-footer">
                    <div class="form-row">
                        <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                            <input type="submit" value="submit" class="btn btn-plum form-control">
                        </div>
                        <div class="col-12 col-sm-12 col-lg-6 col-xl-6">
                            <a href="{{route('admin.category.index')}}" class="btn btn-plum form-control">Back</a>
                        </div>
                    </div>
               </div>
            </div>
           </form>
        </div>
    </div>
</div>
@endsection

resources/views/cpadmin/modules/bill/index.blade.php
@extends('cpadmin.master')
@section('content')
@section('title','List Bill')
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
          <div id="bg-purple" class="card">
             <div class="card-header">
                 <div class="row">
                    <div class="col-12 col-lg-12 col-sm-12 col-xl-12">
                       <div class="card-title text-center">
                          Danh Sách Bill
                       </div>
                    </div>
                 </div>
                 <div class="row">
                      <div class="col-6 col-xl-6 col-sm-auto col-lg-auto">
                           <a href="{{route('admin.bill.create')}}" class="btn btn-plum">Tạo Bill</a>
                     </div>
                 </div>
             </div>
             <div  class="card-body">
               <table id="example1" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>ID</th>
                            <th>Giảm giá </th>
                        
                            <th>Tình trạng</th>
                            <th>GHI chú</th>
                           
                            <th>Thời gian tạo</th>
                            <th>Thời gian cập nhật</th>
                            <th>Chỉnh Sửa Bill</th>
                            <th>Xóa Bill</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($bills as $itembills)
                        <tr>
                            <td>{{$loop->iteration}}</td>
                            <td>{{$itembills->id}}</td>
                            <td>5000</td>
                            <td>
                              @if($itembills->status == 1)
                                Chưa thanh toán
                                @else 
                                Thanh toán
                              @endif
                            </td>
                            <td>{{$itembills->note}}</td>
                            <td>{{$itembills->created_at}}</td>
                            <td>{{$itembills->updated_at}}</td>
                           
                            <th title="Chỉnh Sửa Bill"><a href="{{route('admin.bill.edit',['id' =>$itembills->id])}}" >Chỉnh Sửa</a></th>
                            <th title="Xóa Bill "><a href="{{route('admin.bill.destroy',['id' =>$itembills->id])}}" onclick="return acceptDelete('Bạn Có chắc Muốn Xóa Bill Này')">Xóa</a></th>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                       <tr>
                        <th>STT</th>
                        <th>ID</th>
                        <th>Giảm giá </th>
                      
                        <th>Tình trạng</th>
                        <th>GHI chú</th>
                      
                        <th>Thời gian tạo</th>
                        <th>Thời gian cập nhật</th>
                        <th>Chỉnh Sửa Bill</th>
                        <th>Xóa Bill</th>
                       </tr>
                    </tfoot>
               </table>
             </div>
             <div class="card-footer">
               <div class="row">
                  <div class="col-12 col-sm-12 col-lg-auto col-xl-auto">
                    <a href="{{route('admin.category.create')}}" class="btn btn-plum">Tạo Danh Mục</a>
                  </div>
               </div>
             </div>
          </div>
        </div>
    </div>
</div>

@endsection

resources/views/cpadmin/modules/bill/list.blade.php
@extends('cpadmin.master')
@section('content')
@section('title','Danh Sách Bill')
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-sm-12 col-lg-12 col-xl-12">
          <div id="bg-purple" class="card">
             <div class="card-header">
                 <div class="row">
                    <div class="col-12 col-lg-12 col-sm-12 col-xl-12">
                       <div class="card-title text-center">
                          Danh Sách Bill
                       </div>
                    </div>
                 </div>
             </div>
             <div  class="card-body">
               <table id="example1" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Giảm giá </th>
                            <th>Tình trạng</th>
                            <th>GHI chú</th>
                            <th>Thời gian vào</th>
                            <th>Thời gian rời khỏi</th>
                            <th>Xem Chi Tiết </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{$bill->id}}</td>
                            <td>5000</td>
                            <td>
                              @if($bill->status == 1)
                                Thanh Toán
                                @else 
                                Chưa Tanh Toán
                              @endif
                            </td>
                            <td>{{$bill->note}}</td>
                            <td>{{$bill->created_at}}</td>
                            <td>{{$bill->updated_at}}</td>
                            <td><a href="{{route('admin.billinfo.list',['bill_id'=>$bill->id])}}">Xem Chi Tiết</a></td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <th>ID</th>
                        <th>Giảm giá </th>
                        <th>Tình trạng</th>
                        <th>GHI chú</th>
                        <th>Thời gian Vào</th>
                        <th>Thời gian rời khỏi</th>
                        <th>Xem Chi Tiết </th>
                       </tr>
                    </tfoot>
               </table>
             </div>
             <div class="card-footer">
               <div class="row">
                  <div class="col-12 col-sm-12 col-lg-auto col-xl-auto">
                    <a href="{{route('admin.table.index')}}" class="btn btn-plum">Back</a>
                  </div>
               </div>
             </div>
          </div>
        </div>
    </div>
</div>

@endsection